import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@My_UIfooter/main";
import NavBar from "@My_UInavbar/main";
import CartInit from "lib/cart/initCart";
import CartDrawer from "@My_UIcart/CartDrawer.client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />
        {children}
        <Footer />
        <CartInit />
        <CartDrawer />
      </body>
    </html>
  );
}
