import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "My_UI/footer/main";
import NavBar from "My_UI/navbar/main";
import CartInit from "lib/cart/initCart";
import CartDrawer from "My_UI/cart/CartDrawer.client";
import { Suspense } from "react";
import { Loader } from "lucide-react";
import dynamic from "next/dynamic";

const NotifyPortal = dynamic(() => import("lib/notify"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Building innovation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />
        {children}
        <Footer />
        <CartInit />
        <CartDrawer />
        <div id="modal-root" />
        <div id="notify-container" />
        <Suspense fallback={<Loader />}>
          <NotifyPortal />
        </Suspense>
      </body>
    </html>
  );
}
